### ISSUE TITLE
Now there is an error with meta methods

### ISSUE THREAD

**Issue by mingodad** [qtiuto/lua-for-android#7]
Hello !
Thanks for fix the issues reported before.
But now with the changes you've made to the meta methods it compiles fine when applied to the original lua-ffi but when try to test it "lua test.lua" we get this error:
```
ljs: test.ljs:685: type struct vls has no member key
stack traceback:
	[C]: in metamethod '__index'
	test.ljs:685: in main chunk
	[C]: in ?
```
Note I'm using it with https://github.com/mingodad/ljs but otherwise it's the same in Lua. And it was working before the latest changes.

Cheers !

**Comment by qtiuto** [comment]
For my optimzation, I assume that the metatable should be changed after set
by ffi.metatype. If you change the metatable, reset it by ffi.metatype. For
the lua state, I do the similar optimzation. Howerver, I can monitor the
change for table in the lua State while I can not do that in the ffi
library. Moreover, I'm sorry that the error for the io.tmpfile is not
induced by the incompatiblity but the limitation enforced by the android
platform. I have fixed the problem by overriding the c library function
tmpfile by something like File.createTempFile in java.

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月16日周三 16:59写道：

**Comment by qtiuto** [comment]
@mingodad

**Comment by mingodad** [comment]
I'm testing the meta method optimisation on ubuntu x64 but I can not get it to work and it segfaults with this sample:
```
local ffi = require("ffi");

ffi.cdef [[
struct vls {
    struct {
        char a;
        struct {
            char b;
            char v[?];
        } c;
    } d;
};
struct vls2 {
    char pad;
    union {
        uint8_t a;
        uint16_t b;
    };
};
]]

assert(ffi.sizeof('struct vls', 3) == 5)
assert(ffi.sizeof(ffi.new('struct vls', 4).d.c) == 5)
assert(ffi.offsetof('struct vls2', 'a') == 2)
assert(ffi.sizeof('struct vls2') == 4)

local mt = {}

local vls = ffi.new(ffi.metatype('struct vls', mt), 1)
```
Cheers !

**Comment by qtiuto** [comment]
Now it should work fine with lastest two commit.

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月17日周四 17:24写道：

**Comment by mingodad** [comment]
Does the sample code above works to you ?

**Comment by qtiuto** [comment]
After fix, it works. it's just a index bug. I forgot to decrease index
after changing lua_rawget to lua_rawgeti. And I have fixed the way
compiling the metatable to ensure it starts at 1 rather than zero.

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月17日周四 19:53写道：

**Comment by mingodad** [comment]
Hello !
I just did a pull request and tested again but still getting segfault.

**Comment by mingodad** [comment]
Here is the whole folder I'm testing just in case you can see/test too.
[luaffib-arm-full.zip](https://github.com/qtiuto/lua-for-android/files/2768545/luaffib-arm-full.zip)

**Comment by qtiuto** [comment]
The small fix will work for you.I just forgot to handle empty metatable
case which won't generate a valid  compiled metatanle on the stack. Now, I
push nil on the stack.

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月17日周四 20:08写道：

**Comment by mingodad** [comment]
Hello !
Indeed with the last fix it do not segfault anymore, but when we try to run test.lua it doesn't go forward.
I understand that you said that we need to reset the ffi.metatype and I did for the first occurrence but when I did for the next one it gives another error with meta method "__add".

Can you make it work with test.lua ?
If so could you share what adjusts you did to make it work ?
Cheers !

**Comment by qtiuto** [comment]
You can add the below to set the metatable again.
ffi.metatype('struct vls', mt)
Index for call is unfixed in the previous commit and I fix it in the later
commit. In the laset commit I fix mode for arm64. Cheers!

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月17日周四 21:18写道：

**Comment by mingodad** [comment]
Thank you for share it !
Doing so give now the following error :
```
test.lua 
Running test
lua: test.lua:734: only function callbacks are callable
stack traceback:
	[C]: in local 'vls'
	test.lua:734: in main chunk
	[C]: in ?
```
test.lua at that position:
```
check(vls <= u64(6), true)
check(-vls, -5)
local a,b = vls('6') -- ??? here is the error
check(a, '__call')
```
Are you testing the test.lua ?

Cheers !

**Comment by qtiuto** [comment]
Sorry, I just close my vpn then. The error is fixed now in the lastest two
commit.

Domingo Alvarez Duarte <notifications@github.com> 于 2019年1月17日周四 22:13写道：
